# Generated by Omarchy for THPM.
c.colors.webpage.bg = '#0e091d'
c.colors.completion.fg = '#14B9B5'
c.colors.completion.odd.bg = '#0b0716'
c.colors.completion.even.bg = '#0e091d'
c.colors.completion.match.fg = '#04C5F0'
c.colors.statusbar.normal.bg = '#07050f'
c.colors.statusbar.normal.fg = '#14B9B5'
