-- Monitors generated by display-tui
hl.monitor({
  output = "eDP-1",
  mode = "1920x1280@60",
  position = "0x0",
  scale = 1.25,
  transform = 0
})

-- Workspace assignments
hl.workspace_rule({ workspace = "1", monitor = "eDP-1", default = true })
