# Application bindings
bindd = SHIFT ALT, T, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = qutebrowser

bindd = SUPER SHIFT, T, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus "deezer-enhanced %"
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, RETURN, Activity, exec, omarchy-launch-tui btop
#bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Github, exec, $browser "https://Github.com/"
bindd = SUPER SHIFT, H, Github-Desktop, exec, /usr/bin/github-desktop-plus %U bindd = SUPER SHIFT, D, Discord, exec, uwsm-app -- equibop

bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "obsidian$" "uwsm-app -- obsidian"
bindd = SUPER SHIFT, E, E-mail, exec, uwsm-app -- thunderbird


# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, Odysseus, exec, $browser http://localhost:7000/
bindd = SUPER SHIFT, Y, YouTube, exec, $browser "https://youtube.com/"
bindd = SUPER SHIFT, X, Twitter, exec, $browser "https://x.com/"

bindd = SUPER, DELETE, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER CTRL, GRAVE, Extract text (OCR) from screenshot, exec, omarchy-capture-text-extraction
