# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.local/state/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu
cursor {
    no_hardware_cursors = true
}
# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = GTK_THEME=Adwaita-dark
exec-once = headsetcontrol -s 115
# Odysseus web app
exec-once = tmux new-session -d -s odysseus -c ~/odysseus/ "source venv/bin/activate.fish && python -m uvicorn app:app --host 0.0.0.0 --port 7000"
#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons   
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:

env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme
# Discord
# exec-once = uwsm app -- discord
windowrulev = workspace 2, class:equibop # Equibop discord client

# polkit for password prompts
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
