# Generated by Omarchy from a THPM-owned template.
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --color=bg:#0e091d,bg+:#14B9B5,fg:#14B9B5,fg+:#11AEB3,hl:#BE3F50,hl+:#04C5F0,info:#FF7F41,prompt:#9147a8,pointer:#7cd699,marker:#E20342,spinner:#7cd699,header:#c53253"
