# Generated by Omarchy from a THPM-owned template.
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --color=bg:#1C1E26,bg+:#2E303E,fg:#CBCED0,fg+:#E3E6EE,hl:#26BBD9,hl+:#3FC4DE,info:#59E1E3,prompt:#EE64AC,pointer:#FAB795,marker:#29D398,spinner:#FAC29A,header:#6F6F70"
